image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install --dev

stages:
  - build
  - deploy

build:
  script:
    - npm build
  stage: build
  artifacts:
    paths:
      - assets/
      - partials/
      - author.hbs
      - default.hbs
      - index.hbs
      - page.hbs
      - post.hbs
      - tag.hbs

deploy:
  script:
    - echo "Deploying... "
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB_DEPLOY_KEY")
    - mkdir -p ~/.ssh
    - scp -o StrictHostKeyChecking=no -r assets/ partials/ author.hbs default.hbs index.hbs page.hbs post.hbs tag.hbs gitlab-deploy@node1.makerforce.io:blog-theme/
  stage: deploy
  only:
    - master
