image: serverwentdown/alpine-node:lts

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install --dev
    - npm run build
  artifacts:
    paths:
      - assets/
      - partials/
      - author.hbs
      - default.hbs
      - index.hbs
      - page.hbs
      - post.hbs
      - tag.hbs
      - package.json

deploy:
  stage: deploy
  script:
    - echo "Deploying... "
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB_DEPLOY_KEY")
    - mkdir -p ~/.ssh
    - scp -o StrictHostKeyChecking=no -r assets/ partials/ author.hbs default.hbs index.hbs page.hbs post.hbs tag.hbs amp.hbs package.json gitlab-deploy@node1.makerforce.io:blog-theme/
    - ssh gitlab-deploy@node1.makerforce.io sudo -u hosting XDG_RUNTIME_DIR=/run/user/\`id -u hosting\` /bin/systemctl --user restart ghost
  only:
    - master
