name: Deploy Theme
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - name: Install theme dependencies
        run: npm install
      - name: Download third-party components
        run: npm run setup
      - name: Build Ghost theme
        run: |
          npm run build
          npm run zip
      - name: Deploy Ghost theme
        uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          file: blog-theme.zip
